name: main-workflow
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  job1:
    runs-on: self-hosted
    steps:
      - name: run a single command on ubuntu machine
        run: |
          echo running workflow in main branch
          hostname
          sleep 5
          touch /tmp/sean-devop_20230613
      - name: second step
        run: echo "hello from second condition based step"
        if: github.event_name == 'push'
      - name: third step
        run: echo "hello from 3rd step"
