name: main-workflow2
on: 
  push:
    branches: [ "main" ]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: run a single command on ubuntu machine
        run: echo running second workflow on main branch
