name: Artifacts
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir -p sean-dir
      - run: echo hello > sean-dir/world.txt
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: sean-dir/world.txt
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: my-artifact
      - run: |
          ls -l
          cat world.txt
