name: Greeting on variable day
on:
  push
env:
  DAY_OF_WEEK: Monday
  a: b
  First_name: Sean
jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
      First_name: Yvette
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK! $a"
        env:
          First_Name: John
          Greeting: Salutations,
      - name: repo variables
        run: |
          echo "Hi, value of var is ${{vars.var1}} and today is ${{vars.day}}"
          echo "${{secrets.secret1}}"
